### PR TITLE
print git hash used in accProcess

### PR DESCRIPTION
**Pull request by R-Walmsley**
A first attempt at printing some of the details of processing as part of the summary. Feedback very welcome! (And please don't merge yet, see below for why). 

TODO: 
- Test in different settings (e.g. installed/non-installed). 
- This only does it for accProcess.py, which means: 1. It doesn't actually tell you which version of accelerometer has been used for different processing (although according to the rules for finding python modules, it should be this one. 2. It doesn't help with any of the other functions in the package (that's a "TODO list" item). 
- The regression test will evidently need updating!
- Probably worth testing for multiple environments as I guess it might be a bit sensitive to that sort of thing.

### CODE REVIEW

**Comment by aidendoherty** [comment]
Looks fine to me at face value. For full reproducibility/logging, would we also want to output the input parameters too?

**Comment by R-Walmsley** [comment]
Hi @aidendoherty 

Yes in theory. That said, they are more usually stored because typically there is the text file with commands, so probably not the priority. 

Actually this is pretty far from full reproducibility, as all this is checking is the git hash of the accProcess.py file used. I guess in theory that could end up calling a different version of `accelerometer` (although I think only if the user had done something funky with the file structure). 

So maybe how exactly this should work is something for a quick discussion in one of our biobankAccelerometerAnalysis meetings?

**Comment by angerhang** [comment]
> Hi @aidendoherty
> 
> Yes in theory. That said, they are more usually stored because typically there is the text file with commands (although defaults won't be obvious from this), so maybe not the priority.
> 
> Actually this is pretty far from full reproducibility, as all this is checking is the git hash of the accProcess.py file used. I guess in theory that could end up calling a different version of `accelerometer` (although I think only if the user had done something funky with the file structure).
> 
> So maybe how exactly this should work is something for a quick discussion in one of our biobankAccelerometerAnalysis meetings?

Being able to know which version of BBAA is certainly great! Thanks for the initiatives :D 

In fact once we move to using Hydra as part of the pythonization move, all the input parameters will automatically saved so we don't need to spend time doing something that will be better done at a later date.

In terms of this PR, what is the expected behaviour if the command fails? Sometimes the end users will have Git installed. 

Yeah we could potentially discuss this really quick in the meeting but printing out the Github hash is the least that we can do. Better than nothing right even though not bullet-proof ;D

**Comment by chanshing** [comment]
Closing as we now version our packages in Pip

**Pull request closed without merging**
